### ISSUE TITLE
ERROR in ./app/scripts/app.js

### ISSUE THREAD

**Issue by cevin** [ipfs/webui#269]
```
ERROR in ./app/scripts/app.js
Module build failed: Error: Cannot find module './path'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/cevin/webui/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-types/node_modules/babel-traverse/lib/context.js:13:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/cevin/webui/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-types/node_modules/babel-traverse/lib/index.js:18:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/cevin/webui/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-types/lib/converters.js:38:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/cevin/webui/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-types/lib/index.js:576:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
 @ multi main
```

**Comment by dignifiedquire** [comment]
Could you provide some details about your environment and how you are running the webui please?

**Comment by cevin** [comment]
```
npm install
npm update
```

```
npm run build
```

**Comment by dignifiedquire** [comment]
What node/npm versions are you running?

**Comment by diasdavid** [comment]
Couldn't reproduce. @cevin let us know if you still run into this issue. Thanks for the report.
