### ISSUE TITLE
Not being able to `make publish`

### ISSUE THREAD

**Issue by diasdavid** [ipfs/webui#74]
```
» make publish                                                                                            
rm -rf build
rm -rf publish
npm install
mkdir publish
cp -r static publish
cp -r html/index.html publish
node_modules/.bin/browserify -t reactify . > publish/bundle.js
SyntaxError: Unexpected token (30703:1) while parsing /Users/david/Documents/Code/ipfs/webui/node_modules/three/three.js while parsing file: /Users/david/Documents/Code/ipfs/webui/node_modules/three/three.js
    at DestroyableTransform.end [as _flush] (/Users/david/Documents/Code/ipfs/webui/node_modules/browserify/node_modules/insert-module-globals/index.js:75:21)
    at DestroyableTransform.<anonymous> (/Users/david/Documents/Code/ipfs/webui/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at prefinish (/Users/david/Documents/Code/ipfs/webui/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:450:12)
    at finishMaybe (/Users/david/Documents/Code/ipfs/webui/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:458:7)
    at endWritable (/Users/david/Documents/Code/ipfs/webui/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at DestroyableTransform.Writable.end (/Users/david/Documents/Code/ipfs/webui/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DestroyableTransform.onend (/Users/david/Documents/Code/ipfs/webui/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.j
```

**Comment by krl** [comment]
@diasdavid i think this can be fixed by updating the dep of three.js to the latest version.

**Comment by diasdavid** [comment]
@krl thanks, that worked.

But now from the resulting `hash`:

```
http://localhost:5001/ipfs/QmXLEfJtDAiaatZyBB8TqT7Q7rhU99hSTvLRpuf7hLSvGS
http://gateway.ipfs.io/ipfs/QmXLEfJtDAiaatZyBB8TqT7Q7rhU99hSTvLRpuf7hLSvGS
```

I get 403 on local gateway and 'infinite load' on the gateway.ipfs.io . My local Node is (and was running)

**Comment by jbenet** [comment]
> @diasdavid i think this can be fixed by updating the dep of three.js to the latest version. 

maybe that should be merged to master

**Comment by jbenet** [comment]
@diasdavid you may need 
```
ipfs daemon --unrestricted-api 
```

**Comment by diasdavid** [comment]
@jbenet could you give me `push permissions` to this repo?

**Comment by diasdavid** [comment]
> https://github.com/ipfs/webui/pull/75
